config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    resources :reviews, except:[:show,:index]
  end
  root  'movies#index'

get '/delete_movie/:id' => 'movies#destroy'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  has_attached_file :image, styles: { medium: "400x600#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index,:show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews=Review.where(movie_id:@movie.id).order("created_at DESC")
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_movie

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id= @movie.id

      if @review.save
        redirect_to @movie
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to root_path, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie= Movie.find(params[:movie_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
<br>
  <div class="container-fluid">
    <div class="navbar-header">
    <a class="navbar-movie-review btn btn-primary" href="/movies/new">New Movie</a>
    <a class="navbar-movie-review btn btn-primary" href="/users/sign_up">Sign Up|Sign In</a>
    </div>
<div class="nav navbar-nav navbar-right" id="bs-example-navbar-collapse-1">
  <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
</div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header'%>
  <div class="container">
    <% flash.each do |name,msg| %>
    <%= content_tag(:div,msg, class:"alert alert-info")%>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html:{multipart:true}, class: "form-inline" do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :movie_length %><br>
    <%= f.text_field :movie_length %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <br>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
  <h1>Your Favorite Movies Reviewed !!!</h1>
  <p>Sign in to review</p>
  <a href="<%=new_user_registration_path%>" class="btn btn-primary btn-lg">Sign Up</a>
</div>
<% end -%>
<div class="row movies_container">
<% a_var=1 %>
  <% @movies.each do |m| %>
  <% a_var+=1%>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <div class="show-image">
        <%= link_to (image_tag m .image.url(:medium),class:'image'), m %>

        <div class="display-me">
        <!--
          <%= button_to "Delete Movie", "/delete_movie/#{m.id}", :method => "get", class: 'btn btn-danger'%>
          //Needs no javascript, no ajax
        -->

        <!-- Following button link uses ajax -->
        <a class="btn btn-danger delete_movie_link" data-id="<%= m.id %>" href="delete_movie/<%= m.id%>">Delete</a>
        </div>

      </div>
    </div>
<%= if (!(a_var%4)) then simple_format("\n"); end%>
  </div>

  <% end %>

  <script>

$.ajax({
  url: 'delete_movie/#{m.id}',
  type: 'GET',
  dataType: 'Intelligent Guess',
  data: {id: $(this).attr('data-id')},
})
.done(function() {
  $(this).parents('div').remove();
  console.log("success");
})
.fail(function() {
  console.log("error");
})
.always(function() {
  console.log("complete");
});


  </script>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>
<br><br>
<%= link_to 'Back', movies_path,class:'btn btn-primary' %>

app/views/movies/show.html.erb
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <%= link_to "Home",movies_path,class:'btn btn-primary center-block'%>
          <br><br>
          <div class="col-sm-5">
            <%= image_tag @movie.image.url(:medium) %>
          </div>
          <div class="col-sm-6">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th><strong>Title</strong> </th>
                  <td><%= @movie.title %></td>
                </tr>
                <tr>
                  <th><strong> Description</strong> </th>
                  <td><%= @movie.description%></td>
                </tr>
                <tr>
                  <th><strong>Movie Length</strong> </th>
                  <td><%= @movie.movie_length%></td>
                </tr>
                <tr>
                  <th><strong>Director</strong> </th>
                  <td><%=@movie.director%></td>
                </tr>
                <th><strong>Rating</strong> </th>
                <td><%= @movie.rating%></td>
              </tr>
            </thead>
            <tbody>
              <tr class="info">
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review",new_movie_review_path(@movie),class:"btn btn-primary" %> |
          <%= link_to 'Edit movie', edit_movie_path(@movie),class:"btn btn-primary" %></div>
        </div>
        <br><br><br>
        <div>
          <div class="rows">
            <% @reviews.each do |r|%>
            <div class="review">
              <strong><%= r.user.email%></strong><br>
              Rating: <div class="star-rating" data-score=<%=r.rating%>></div><br>
              <%= r.comment%><br><br><br>
              <%end%></div></div>
            </div>
          </div>



          <%= link_to 'Back', movies_path,class:"btn btn-primary center-block" %>


          <script >
            $('.star-rating').raty
            (
            {
              path: '/assets/',
              readOnly: true,
              score: function()
              {
                return $(this).attr('data-score');
              }
            });
          </script>

app/views/reviews/_form.html.erb
<%= form_for([@movie,@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', root_path %> |
<%= link_to 'Back', # %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path(@movie) %>